- name: Install repo dnf
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ repo_filename }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}.repo"
    - "{{ ansible_distribution | lower }}.repo"

- name: Install package
  yum:
    name: "{{ pkg_name }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  #whith_items: "{{ pkg_name }}"

